namespace("sprocket.SprocketsFaces", {}, () => {
  const eyes = [
    ["closed-eyes"],
    ["blink-eyes"],
    ["sad-eyes"],
    ["angry-eyes"],
    ["angry-raised-left"],
    ["angry-raised-right"],
    ["mellow-eyed"],
    ["raised-eyes"],
    ["mellow-raised-left"],
    ["mellow-raised-right"],
    ["side-eyed-left"],
    ["side-eyed-right"],
    ["wide-eyed"],
    ["dollar-eyed"],
    ["heart-eyes"],
    ["sad-wink-left"],
    ["sad-wink-right"],
    ["mellow-wink-left"],
    ["mellow-wink-right"],
  ];
  const mouths = [
    ["closed-smile"],
    ["teeth-smile"],
    ["open-smile"],
    ["open-smile", "tongue"],
    ["thin-lipped"],
    ["gasp"],
    ["wide-open"],
    ["wide-open", "tongue"],
    ["closed-frown"],
    ["teeth-frown"],
    ["open-frown"],
    ["open-frown", "tongue"],
  ]
  const eyesAndMouths = [
    ["raised-eyes", "gasp"],
    ["wide-eyed", "gasp"],
    ["dollar-eyed", "gasp"],
    ["heart-eyes", "gasp"],
    ["closed-eyes", "closed-smile"],
    ["blink-eyes", "closed-smile"],
    ["sad-eyes", "closed-smile"],
    ["angry-eyes", "closed-smile"],
    ["mellow-eyed", "closed-smile"],
    ["raised-eyes", "closed-smile"],
    ["side-eyed-left", "closed-smile"],
    ["side-eyed-right", "closed-smile"],
    ["wide-eyed", "closed-smile"],
    ["dollar-eyed", "closed-smile"],
    ["heart-eyes", "closed-smile"],
    ["sad-wink-left", "closed-smile"],
    ["sad-wink-right", "closed-smile"],
    ["mellow-wink-left", "closed-smile"],
    ["mellow-wink-right", "closed-smile"],
    ["closed-eyes", "teeth-smile"],
    ["blink-eyes", "teeth-smile"],
    ["sad-eyes", "teeth-smile"],
    ["angry-eyes", "teeth-smile"],
    ["mellow-eyed", "teeth-smile"],
    ["raised-eyes", "teeth-smile"],
    ["side-eyed-left", "teeth-smile"],
    ["side-eyed-right", "teeth-smile"],
    ["wide-eyed", "teeth-smile"],
    ["dollar-eyed", "teeth-smile"],
    ["heart-eyes", "teeth-smile"],
    ["sad-wink-left", "teeth-smile"],
    ["sad-wink-right", "teeth-smile"],
    ["mellow-wink-left", "teeth-smile"],
    ["mellow-wink-right", "teeth-smile"],
    ["closed-eyes", "open-smile"],
    ["blink-eyes", "open-smile"],
    ["sad-eyes", "open-smile"],
    ["angry-eyes", "open-smile"],
    ["mellow-eyed", "open-smile"],
    ["raised-eyes", "open-smile"],
    ["side-eyed-left", "open-smile"],
    ["side-eyed-right", "open-smile"],
    ["wide-eyed", "open-smile"],
    ["dollar-eyed", "open-smile"],
    ["heart-eyes", "open-smile"],
    ["sad-wink-left", "open-smile"],
    ["sad-wink-right", "open-smile"],
    ["mellow-wink-left", "open-smile"],
    ["mellow-wink-right", "open-smile"],
    ["closed-eyes", "open-smile", "tongue"],
    ["blink-eyes", "open-smile", "tongue"],
    ["sad-eyes", "open-smile", "tongue"],
    ["angry-eyes", "open-smile", "tongue"],
    ["mellow-eyed", "open-smile", "tongue"],
    ["raised-eyes", "open-smile", "tongue"],
    ["side-eyed-left", "open-smile", "tongue"],
    ["side-eyed-right", "open-smile", "tongue"],
    ["wide-eyed", "open-smile", "tongue"],
    ["dollar-eyed", "open-smile", "tongue"],
    ["heart-eyes", "open-smile", "tongue"],
    ["sad-wink-left", "open-smile", "tongue"],
    ["sad-wink-right", "open-smile", "tongue"],
    ["mellow-wink-left", "open-smile", "tongue"],
    ["mellow-wink-right", "open-smile", "tongue"],
    ["closed-eyes", "thin-lipped"],
    ["blink-eyes", "thin-lipped"],
    ["sad-eyes", "thin-lipped"],
    ["angry-eyes", "thin-lipped"],
    ["angry-raised-left", "thin-lipped"],
    ["angry-raised-right", "thin-lipped"],
    ["mellow-eyed", "thin-lipped"],
    ["raised-eyes", "thin-lipped"],
    ["mellow-raised-left", "thin-lipped"],
    ["mellow-raised-right", "thin-lipped"],
    ["side-eyed-left", "thin-lipped"],
    ["side-eyed-right", "thin-lipped"],
    ["wide-eyed", "thin-lipped"],
    ["dollar-eyed", "thin-lipped"],
    ["heart-eyes", "thin-lipped"],
    ["closed-eyes", "wide-open"],
    ["blink-eyes", "wide-open"],
    ["sad-eyes", "wide-open"],
    ["angry-eyes", "wide-open"],
    ["mellow-eyed", "wide-open"],
    ["raised-eyes", "wide-open"],
    ["side-eyed-left", "wide-open"],
    ["side-eyed-right", "wide-open"],
    ["wide-eyed", "wide-open"],
    ["dollar-eyed", "wide-open"],
    ["heart-eyes", "wide-open"],
    ["closed-eyes", "wide-open", "tongue"],
    ["blink-eyes", "wide-open", "tongue"],
    ["sad-eyes", "wide-open", "tongue"],
    ["angry-eyes", "wide-open", "tongue"],
    ["mellow-eyed", "wide-open", "tongue"],
    ["raised-eyes", "wide-open", "tongue"],
    ["side-eyed-left", "wide-open", "tongue"],
    ["side-eyed-right", "wide-open", "tongue"],
    ["wide-eyed", "wide-open", "tongue"],
    ["dollar-eyed", "wide-open", "tongue"],
    ["heart-eyes", "wide-open", "tongue"],
    ["closed-eyes", "closed-frown"],
    ["blink-eyes", "closed-frown"],
    ["sad-eyes", "closed-frown"],
    ["angry-eyes", "closed-frown"],
    ["angry-raised-left", "closed-frown"],
    ["angry-raised-right", "closed-frown"],
    ["mellow-eyed", "closed-frown"],
    ["raised-eyes", "closed-frown"],
    ["mellow-raised-left", "closed-frown"],
    ["mellow-raised-right", "closed-frown"],
    ["side-eyed-left", "closed-frown"],
    ["side-eyed-right", "closed-frown"],
    ["wide-eyed", "closed-frown"],
    ["dollar-eyed", "closed-frown"],
    ["heart-eyes", "closed-frown"],
    ["closed-eyes", "teeth-frown"],
    ["blink-eyes", "teeth-frown"],
    ["sad-eyes", "teeth-frown"],
    ["angry-eyes", "teeth-frown"],
    ["angry-raised-left", "teeth-frown"],
    ["angry-raised-right", "teeth-frown"],
    ["mellow-eyed", "teeth-frown"],
    ["raised-eyes", "teeth-frown"],
    ["mellow-raised-left", "teeth-frown"],
    ["mellow-raised-right", "teeth-frown"],
    ["side-eyed-left", "teeth-frown"],
    ["side-eyed-right", "teeth-frown"],
    ["wide-eyed", "teeth-frown"],
    ["dollar-eyed", "teeth-frown"],
    ["heart-eyes", "teeth-frown"],
    ["closed-eyes", "open-frown"],
    ["blink-eyes", "open-frown"],
    ["sad-eyes", "open-frown"],
    ["angry-eyes", "open-frown"],
    ["mellow-eyed", "open-frown"],
    ["raised-eyes", "open-frown"],
    ["side-eyed-left", "open-frown"],
    ["side-eyed-right", "open-frown"],
    ["wide-eyed", "open-frown"],
    ["dollar-eyed", "open-frown"],
    ["heart-eyes", "open-frown"],
    ["closed-eyes", "open-frown", "tongue"],
    ["blink-eyes", "open-frown", "tongue"],
    ["sad-eyes", "open-frown", "tongue"],
    ["angry-eyes", "open-frown", "tongue"],
    ["mellow-eyed", "open-frown", "tongue"],
    ["raised-eyes", "open-frown", "tongue"],
    ["side-eyed-left", "open-frown", "tongue"],
    ["side-eyed-right", "open-frown", "tongue"],
    ["wide-eyed", "open-frown", "tongue"],
    ["dollar-eyed", "open-frown", "tongue"],
    ["heart-eyes", "open-frown", "tongue"],
  ];
  const eyesAndMouthsWithTears = [
    ["wide-eyed", "gasp"],
    ["dollar-eyed", "gasp"],
    ["heart-eyes", "gasp"],
    ["closed-eyes", "closed-smile"],
    ["blink-eyes", "closed-smile"],
    ["sad-eyes", "closed-smile"],
    ["wide-eyed", "closed-smile"],
    ["dollar-eyed", "closed-smile"],
    ["heart-eyes", "closed-smile"],
    ["blink-eyes", "teeth-smile"],
    ["sad-eyes", "teeth-smile"],
    ["wide-eyed", "teeth-smile"],
    ["dollar-eyed", "teeth-smile"],
    ["heart-eyes", "teeth-smile"],
    ["blink-eyes", "open-smile"],
    ["sad-eyes", "open-smile"],
    ["wide-eyed", "open-smile"],
    ["dollar-eyed", "open-smile"],
    ["heart-eyes", "open-smile"],
    ["blink-eyes", "wide-open"],
    ["sad-eyes", "wide-open"],
    ["angry-eyes", "wide-open"],
    ["wide-eyed", "wide-open"],
    ["dollar-eyed", "wide-open"],
    ["heart-eyes", "wide-open"],
    ["blink-eyes", "wide-open", "tongue"],
    ["sad-eyes", "wide-open", "tongue"],
    ["angry-eyes", "wide-open", "tongue"],
    ["wide-eyed", "wide-open", "tongue"],
    ["dollar-eyed", "wide-open", "tongue"],
    ["heart-eyes", "wide-open", "tongue"],
    ["closed-eyes", "closed-frown"],
    ["blink-eyes", "closed-frown"],
    ["sad-eyes", "closed-frown"],
    ["angry-eyes", "closed-frown"],
    ["wide-eyed", "closed-frown"],
    ["dollar-eyed", "closed-frown"],
    ["heart-eyes", "closed-frown"],
    ["blink-eyes", "teeth-frown"],
    ["sad-eyes", "teeth-frown"],
    ["angry-eyes", "teeth-frown"],
    ["wide-eyed", "teeth-frown"],
    ["dollar-eyed", "teeth-frown"],
    ["heart-eyes", "teeth-frown"],
    ["blink-eyes", "open-frown"],
    ["sad-eyes", "open-frown"],
    ["angry-eyes", "open-frown"],
    ["wide-eyed", "open-frown"],
    ["dollar-eyed", "open-frown"],
    ["heart-eyes", "open-frown"],
    ["blink-eyes", "open-frown", "tongue"],
    ["sad-eyes", "open-frown", "tongue"],
    ["angry-eyes", "open-frown", "tongue"],
    ["wide-eyed", "open-frown", "tongue"],
    ["dollar-eyed", "open-frown", "tongue"],
    ["heart-eyes", "open-frown", "tongue"],
  ];
  const eyesAndMouthsWithSweat = [
    ["wide-eyed", "gasp"],
    ["dollar-eyed", "gasp"],
    ["heart-eyes", "gasp"],
    ["sad-eyes", "closed-smile"],
    ["blink-eyes", "teeth-smile"],
    ["sad-eyes", "teeth-smile"],
    ["blink-eyes", "open-smile"],
    ["sad-eyes", "open-smile"],
    ["sad-wink-left", "open-smile"],
    ["sad-wink-right", "open-smile"],
    ["blink-eyes", "open-smile", "tongue"],
    ["sad-eyes", "open-smile", "tongue"],
    ["sad-wink-left", "open-smile", "tongue"],
    ["sad-wink-right", "open-smile", "tongue"],
    ["closed-eyes", "thin-lipped"],
    ["sad-eyes", "thin-lipped"],
    ["angry-eyes", "thin-lipped"],
    ["wide-eyed", "thin-lipped"],
    ["dollar-eyed", "thin-lipped"],
    ["heart-eyes", "thin-lipped"],
    ["blink-eyes", "wide-open", "tongue"],
    ["sad-eyes", "wide-open", "tongue"],
    ["blink-eyes", "closed-frown"],
    ["sad-eyes", "closed-frown"],
    ["angry-eyes", "closed-frown"],
    ["mellow-eyed", "closed-frown"],
    ["wide-eyed", "closed-frown"],
    ["blink-eyes", "teeth-frown"],
    ["sad-eyes", "teeth-frown"],
    ["angry-eyes", "teeth-frown"],
    ["mellow-eyed", "teeth-frown"],
    ["wide-eyed", "teeth-frown"],
    ["closed-eyes", "open-frown"],
    ["blink-eyes", "open-frown"],
    ["sad-eyes", "open-frown"],
    ["angry-eyes", "open-frown"],
    ["mellow-eyed", "open-frown"],
    ["wide-eyed", "open-frown"],
    ["dollar-eyed", "open-frown"],
    ["heart-eyes", "open-frown"],
    ["closed-eyes", "open-frown", "tongue"],
    ["blink-eyes", "open-frown", "tongue"],
    ["sad-eyes", "open-frown", "tongue"],
    ["angry-eyes", "open-frown", "tongue"],
    ["mellow-eyed", "open-frown", "tongue"],
    ["wide-eyed", "open-frown", "tongue"],
    ["dollar-eyed", "open-frown", "tongue"],
    ["heart-eyes", "open-frown", "tongue"],
  ];
  const topAddOns = [
    [],
    ["sweat"],
    ["tears"]
  ]
  const dim = {
    w: 525,
    h: 525
  }
  const emotions = {
    Sick: ["sad-eyes","open-frown","tongue","sweat"],
    Crying: ["sad-eyes","wide-open","tears"],
    Grumpy: ["mellow-eyed","closed-frown"],
    Hungry: ["raised-eyes","wide-open","tongue"],
    Bored: ["side-eyed-right","thin-lipped"],
    Evil: ["angry-eyes","teeth-smile"],
    Starving: ["angry-eyes","open-frown","tongue"],
    Serene: ["closed-eyes","closed-smile"],
    Sleepy: ["blink-eyes","thin-lipped"],
    Happy: ["blink-eyes","teeth-smile"],
    Excited: ["heart-eyes","teeth-smile"],
    Zoomies: ["wide-eyed","open-smile"]
  }
  const fullList = eyesAndMouths.concat(eyesAndMouthsWithTears.map(attrs => {
    return attrs.concat(["tears"]);
  })).concat(eyesAndMouthsWithSweat.map(attrs => {
    return attrs.concat(["sweat"]);
  })).map((attrs) => {
    return ["base"].concat(attrs);
  });
  console.log({ fullList });
  return function (props) {
    var useList;
    if (props.baseOnly) {
      useList = [["base", "thin-lipped", "angry-eyes"]]
    } else {
      useList = Object.entries(emotions);
    }
    return <div className="d-flex flex-wrap justify-content-center w-100">
      {useList.map(([label,refs]) => <div title={label} className={`emoji-${props.emojiScale} m-2`}>
        <svg width="100%" height="100%" viewBox={`0 0 ${dim.w} ${dim.h}`}>
          <rect width={dim.w} height={dim.h} rx="100" ry="100" fill="white" stroke="black" strokeWidth="10" />
          <use href="#base" />
          {refs.map(href => <use href={`#${href}`} />)}
        </svg>
      </div>)}
    </div>
  }
});